<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.6.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Cpu.Tui/Cpu.Tui.csproj" />
    <ProjectReference Include="../../src/Cpu.Tui.Abstractions/Cpu.Tui.Abstractions.csproj" />
    <ProjectReference Include="../../src/Cpu.Tui.Media/Cpu.Tui.Media.csproj" />
    <ProjectReference Include="../../src/Cpu.Core/Cpu.Core.csproj" />
    <ProjectReference Include="../../src/Cpu.Canvas/Cpu.Canvas.csproj" />
    <ProjectReference Include="../../src/Cpu.Apple1/Cpu.Apple1.csproj" />
    <ProjectReference Include="../../src/Cpu.DemoMenu/Cpu.DemoMenu.csproj" />
    <ProjectReference Include="../../src/Cpu.Help/Cpu.Help.csproj" />
    <ProjectReference Include="../../src/Cpu.Image/Cpu.Image.csproj" />
    <ProjectReference Include="../../src/Cpu.Setup/Cpu.Setup.csproj" />
    <ProjectReference Include="../../src/Cpu.Screen/Cpu.Screen.csproj" />
  </ItemGroup>
</Project>
