<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Cpu.Board</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cpu.Core\Cpu.Core.csproj" />
    <ProjectReference Include="..\Mos6502\Mos6502.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="profiles\**\*.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="roms\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Include="fonts\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
